### ISSUE TITLE
change service in main.js

### ISSUE THREAD

**Issue by enlowe** [CoastalResilienceNetwork/benefits_explorer#1]
update service (already created) to:
Dev:
http://dev.services.coastalresilience.org:6080/arcgis/rest/services/Water_Blueprint/Benefits_Explorer/MapServer

Production:
http://services.coastalresilience.org:6080/arcgis/rest/services/Water_Blueprint/Benefits_Explorer/MapServer

...following DM protocol

**Comment by cschneebeck** [comment]
I updated the map service URL in the master branch of the app. Do you want the app developers to build the region to prod or that something you guys want to do?

**Comment by enlowe** [comment]
I think @zferdana will be taking care of rebuilding. Correct?

**Comment by cschneebeck** [comment]
Works for me.
